[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
scanner = { git = "https://github.com/ErnestoRB/Scanner.git", version = "0.1.0" }
serde = { version = "1.0.202", features = ["derive"] }
